In [1]:
import yfinance as yf

In [2]:
msft = yf.Ticker("MSFT")

In [ ]:
msft

## Get all the information about the ticker

In [ ]:
msft.info

## Getting historical data

In [ ]:
""" 
.history() returns a pandas dataframe
:params period='1mo' (1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y, ytd, max)
:params interval='1d' (1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo)
:params start=2025-01-01 (YYYY-MM-DD)
:params end=2025-01-01 (YYYY-MM-DD)
"""
hist = msft.history(period='max')
hist

### Getting dividends and stock splits only

In [ ]:
msft.actions # dividends, stock splits

In [ ]:
msft.dividends

In [ ]:
msft.splits

In [ ]:
msft.major_holders

In [ ]:
msft.institutional_holders

In [ ]:
msft.balance_sheet

In [ ]:
msft.cashflow

In [ ]:
msft.info['open']

In [ ]:
msft.info

In [ ]:
history = msft.history(start='2025-01-05')
history

In [ ]:
old_price = history.iloc[0]['Close']
old_price

In [ ]:
cur_price = history.iloc[-1]['Close']
cur_price

In [ ]:
percent_change = ((cur_price - old_price) / old_price) * 100
percent_change

In [ ]:
fundamental_data = msft.info

In [ ]:
market_data = {
                'Total Assets': fundamental_data.get('totalAssets'),
                '52-Week Low': fundamental_data.get('fiftyTwoWeekLow'),
                '52-Week High': fundamental_data.get('fiftyTwoWeekHigh'),
                '50-Day Average': fundamental_data.get('fiftyDayAverage'),
                '200-Day Average': fundamental_data.get('twoHundredDayAverage'),
                'NAV Price': fundamental_data.get('navPrice'),
                'Currency': fundamental_data.get('currency'),
                'Category': fundamental_data.get('category'),
                'YTD Return': fundamental_data.get('ytdReturn'),
                'Fund Family': fundamental_data.get('fundFamily'),
                'Fund Inception Date': fundamental_data.get('fundInceptionDate'),
                'Legal Type': fundamental_data.get('legalType'),
            }

market_data = {key: value for key, value in market_data.items() if value is not None}
market_data

In [39]:
def preprocess_fundamental_data(raw_data):
        processed_data = {}
        
        for key, value in raw_data.items():
            if value is not None:
                if isinstance(value, (int, float)):
                    processed_data[key] = "{:,}".format(value)
                else:
                    processed_data[key] = value
        
        return processed_data

In [ ]:
processed_data = preprocess_fundamental_data(market_data)
processed_data

In [12]:
data = yf.download('MSFT', start='2024-01-01', end='2025-01-12')[['Close']]
data = data.resample('M').last()
data

[*********************100%***********************]  1 of 1 completed
/var/folders/6f/0jqwktbs509gd4pxbqkkhxyr0000gp/T/ipykernel_26648/1941425420.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  data = data.resample('M').last()

Price            Close
Ticker            MSFT
Date
2024-01-31  394.629028
2024-02-29  411.329041
2024-03-31  418.369507
2024-04-30  387.154846
2024-05-31  413.555328
2024-06-30  445.254639
2024-07-31  416.763092
2024-08-31  416.306702
2024-09-30  429.440399
2024-10-31  405.538269
2024-11-30  423.459991
2024-12-31  421.500000
2025-01-31  418.950012

In [13]:
data = data.reset_index()
data

Price        Date       Close
Ticker                   MSFT
0      2024-01-31  394.629028
1      2024-02-29  411.329041
2      2024-03-31  418.369507
3      2024-04-30  387.154846
4      2024-05-31  413.555328
5      2024-06-30  445.254639
6      2024-07-31  416.763092
7      2024-08-31  416.306702
8      2024-09-30  429.440399
9      2024-10-31  405.538269
10     2024-11-30  423.459991
11     2024-12-31  421.500000
12     2025-01-31  418.950012

In [14]:
# used for removing time part from the date object if present
data['Date'] = data['Date'].apply(lambda x: x.date()) 
data

Price         Date       Close
Ticker                    MSFT
0       2024-01-31  394.629028
1       2024-02-29  411.329041
2       2024-03-31  418.369507
3       2024-04-30  387.154846
4       2024-05-31  413.555328
5       2024-06-30  445.254639
6       2024-07-31  416.763092
7       2024-08-31  416.306702
8       2024-09-30  429.440399
9       2024-10-31  405.538269
10      2024-11-30  423.459991
11      2024-12-31  421.500000
12      2025-01-31  418.950012

In [15]:
data.columns = ['Date', 'Close']
data

          Date       Close
0   2024-01-31  394.629028
1   2024-02-29  411.329041
2   2024-03-31  418.369507
3   2024-04-30  387.154846
4   2024-05-31  413.555328
5   2024-06-30  445.254639
6   2024-07-31  416.763092
7   2024-08-31  416.306702
8   2024-09-30  429.440399
9   2024-10-31  405.538269
10  2024-11-30  423.459991
11  2024-12-31  421.500000
12  2025-01-31  418.950012

In [16]:
data_process = [ {'dates':list(data['Date']), \
            'values':[round(y,2) for y in list(data['Close'])], \
            'name': 'MSFT'}]
data_process

[{'dates': [datetime.date(2024, 1, 31),
   datetime.date(2024, 2, 29),
   datetime.date(2024, 3, 31),
   datetime.date(2024, 4, 30),
   datetime.date(2024, 5, 31),
   datetime.date(2024, 6, 30),
   datetime.date(2024, 7, 31),
   datetime.date(2024, 8, 31),
   datetime.date(2024, 9, 30),
   datetime.date(2024, 10, 31),
   datetime.date(2024, 11, 30),
   datetime.date(2024, 12, 31),
   datetime.date(2025, 1, 31)],
  'values': [394.63,
   411.33,
   418.37,
   387.15,
   413.56,
   445.25,
   416.76,
   416.31,
   429.44,
   405.54,
   423.46,
   421.5,
   418.95],
  'name': 'MSFT'}]

## Technical Analysis

In [1]:
from datetime import date
import yfinance as yf
import numpy as np 
import pandas as pd

end_date = date.today()
end_date_str = "{}-{}-{}".format(end_date.year, end_date.month, end_date.day)
print(end_date_str)

data = yf.download('MSFT', start='2020-01-01', end=end_date_str)

2025-1-12

[*********************100%***********************]  1 of 1 completed

In [2]:
print(type(data))
print(data.head())
print(data.columns)

<class 'pandas.core.frame.DataFrame'>
Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2020-01-02  153.630692  153.735906  151.440346  151.870762  22622100
2020-01-03  151.717743  152.989871  151.182113  151.430809  21116200
2020-01-06  152.109863  152.176824  149.699516  150.244720  20813700
2020-01-07  150.722992  152.722043  150.474311  152.387282  21634100
2020-01-08  153.123779  153.802891  151.076901  152.014252  27746500
MultiIndex([( 'Close', 'MSFT'),
            (  'High', 'MSFT'),
            (   'Low', 'MSFT'),
            (  'Open', 'MSFT'),
            ('Volume', 'MSFT')],
           names=['Price', 'Ticker'])

In [3]:
data.columns = [col[0] for col in data.columns]
print(data.columns)

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [4]:
import ta

# Add technical analysis features

data = ta.add_all_ta_features(data, open="Open", high="High", low="Low", close="Close", volume="Volume", fillna=True)
data.head()

data.dropna(inplace=True)
data

/Users/bryantan/.pyenv/versions/3.12.8/envs/fyp_env/lib/python3.12/site-packages/ta/trend.py:1030: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  self._psar[i] = high2

,Close,High,Low,Open,Volume,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,153.630692,153.735906,151.440346,151.870762,22622100,2.054839e+07,22622100,0.908333,0.000000e+00,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,153.630692,0.000000,0.000000,0.000000
2020-01-03,151.717743,152.989871,151.182113,151.430809,21116200,1.194544e+07,1505900,0.273112,-4.039421e+07,-4.298767,...,-0.099421,-0.019884,-0.079537,-0.533655,-0.106731,-0.426924,152.712637,-1.245160,-1.252978,-1.245160
2020-01-06,152.109863,152.176824,149.699516,150.244720,20813700,3.163397e+07,22319600,0.490054,-3.345768e+07,-13.661714,...,-0.155906,-0.047088,-0.108817,-1.058791,-0.297143,-0.761648,152.435444,0.258454,0.258120,-0.989925
2020-01-07,150.722992,152.722043,150.474311,152.387282,21634100,1.478690e+07,685500,0.171569,-3.296426e+07,6.857317,...,-0.270807,-0.091832,-0.178975,-1.166343,-0.470983,-0.695360,151.665303,-0.911756,-0.915938,-1.892655
2020-01-08,153.123779,153.802891,151.076901,152.014252,27746500,2.870873e+07,28432000,0.251980,-1.873887e+07,8.269569,...,-0.232575,-0.119981,-0.112594,0.931685,-0.190449,1.122135,152.288074,1.592847,1.580295,-0.329955
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-03,423.350006,424.029999,419.540009,421.079987,16662900,1.919189e+09,1265677600,-0.031361,-2.327989e+07,35.703409,...,-0.395157,0.358401,-0.753558,-8.686647,-4.057861,-4.628786,430.415566,1.139572,1.133128,175.563432
2025-01-06,427.850006,434.320007,425.480011,428.000000,20573600,1.909647e+09,1286251200,-0.082482,-6.728303e+06,348.682870,...,-0.412226,0.204276,-0.616502,-7.078875,-4.662064,-2.416811,430.292993,1.062950,1.057341,178.492534
2025-01-07,422.369995,430.649994,420.799988,429.000000,18139100,1.897290e+09,1268112100,-0.105177,-1.996747e+07,-226.714423,...,-0.522772,0.058866,-0.581638,-6.772716,-5.084194,-1.688522,429.698757,-1.280825,-1.289099,174.925531
2025-01-08,424.559998,426.970001,421.540009,423.459991,15054600,1.898981e+09,1283166700,-0.121521,-1.240503e+07,-53.020426,...,-0.563002,-0.065507,-0.497495,-7.796668,-5.626689,-2.169979,429.453148,0.518503,0.517164,176.351029
2025-01-10,418.950012,424.709991,415.019989,424.630005,20186800,1.895169e+09,1262979900,-0.104479,-2.681112e+07,-210.728063,...,-0.692971,-0.191000,-0.501971,-6.296487,-5.760649,-0.535838,428.181690,-1.321365,-1.330172,172.699425

In [5]:
latest_values = data.iloc[-1]
latest_values

Close                4.189500e+02
High                 4.247100e+02
Low                  4.150200e+02
Open                 4.246300e+02
Volume               2.018680e+07
                         ...
momentum_pvo_hist   -5.358380e-01
momentum_kama        4.281817e+02
others_dr           -1.321365e+00
others_dlr          -1.330172e+00
others_cr            1.726994e+02
Name: 2025-01-10 00:00:00, Length: 91, dtype: float64

In [6]:
buy_signal = (
            (latest_values['trend_macd'] > latest_values['trend_macd_signal']) and
            (latest_values['momentum_rsi'] < 30) and
            (latest_values['momentum_stoch_rsi_k'] < 0.2) and
            (latest_values['trend_adx'] > 25) and
            (latest_values['trend_ema_fast'] > latest_values['trend_ema_slow']) and
            (latest_values['trend_sma_fast'] > latest_values['trend_sma_slow']) and
            (latest_values['volume_obv'] > latest_values['volume_obv_mean']) and
            (latest_values['volatility_bbh'] < latest_values['close']) and
            (latest_values['volatility_bbl'] > latest_values['close']) and
            (latest_values['volatility_bbp'] < 0.05) 
        )

sell_signal = (
    (latest_values['trend_macd'] < latest_values['trend_macd_signal']) and
    (latest_values['momentum_rsi'] > 70) and
    (latest_values['momentum_stoch_rsi_k'] > 0.8) and
    (latest_values['trend_adx'] > 25) and
    (latest_values['trend_ema_fast'] < latest_values['trend_ema_slow']) and
    (latest_values['trend_sma_fast'] < latest_values['trend_sma_slow']) and
    
    (latest_values['volatility_bbh'] > latest_values['close']) and
    (latest_values['volatility_bbl'] < latest_values['close']) and
    (latest_values['volatility_bbp'] > 0.95) 
)

In [7]:
if (sell_signal and buy_signal) or (not buy_signal and not buy_signal):
    signal = 'Neutral'
elif buy_signal and not sell_signal:
    signal = 'Buy'
else:
    signal = 'Sell'

technical_analysis = {
    'MACD': latest_values['trend_macd'],
    'MACD Signal': latest_values['trend_macd_signal'],
    'RSI': latest_values['momentum_rsi'],
    'Stoch RSI K': latest_values['momentum_stoch_rsi_k'],
    'ADX': latest_values['trend_adx'],
    'EMA Fast': latest_values['trend_ema_fast'],
    'EMA Slow': latest_values['trend_ema_slow'],
    'SMA Fast': latest_values['trend_sma_fast'],
    'SMA Slow': latest_values['trend_sma_slow'],
    'Volume OBV': latest_values['volume_obv'],
    # 'Volume OBV Mean': latest_values['volume_obv_mean'],
    'BBH': latest_values['volatility_bbh'],
    'BBL': latest_values['volatility_bbl'],
    'BBP': latest_values['volatility_bbp'],
    'Signal': signal,
    # 'Sell Signal': sell_signal
}

technical_analysis

{'MACD': np.float64(-2.97773218518239),
 'MACD Signal': np.float64(-0.8148558140978962),
 'RSI': np.float64(39.84481245163291),
 'Stoch RSI K': np.float64(0.27805838756039636),
 'ADX': np.float64(21.65485513823951),
 'EMA Fast': np.float64(426.72719345222663),
 'EMA Slow': np.float64(429.704925637409),
 'SMA Fast': np.float64(427.100830078125),
 'SMA Slow': np.float64(435.8561518742488),
 'Volume OBV': np.float64(1262979900.0),
 'BBH': np.float64(456.91817349219167),
 'BBL': np.float64(411.8918210146442),
 'BBP': np.float64(0.15675689466311135),
 'Signal': 'Neutral'}

In [8]:
for key, value in technical_analysis.items():
    # check if value is a dict, if so do rounding
    if isinstance(value, float):
        technical_analysis[key] = round(value, 2)

In [9]:
technical_analysis

{'MACD': np.float64(-2.98),
 'MACD Signal': np.float64(-0.81),
 'RSI': np.float64(39.84),
 'Stoch RSI K': np.float64(0.28),
 'ADX': np.float64(21.65),
 'EMA Fast': np.float64(426.73),
 'EMA Slow': np.float64(429.7),
 'SMA Fast': np.float64(427.1),
 'SMA Slow': np.float64(435.86),
 'Volume OBV': np.float64(1262979900.0),
 'BBH': np.float64(456.92),
 'BBL': np.float64(411.89),
 'BBP': np.float64(0.16),
 'Signal': 'Neutral'}